# Generated by Django 4.0.10 on 2023-02-19 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zipcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.IntegerField(blank=True, default=1, null=True)),
                ('locality', models.CharField(max_length=250, null=True)),
                ('settlement', models.CharField(max_length=100, null=True)),
                ('settlement_type', models.CharField(max_length=20, null=True)),
                ('settlement_code', models.IntegerField(null=True)),
                ('zone_type', models.CharField(max_length=20, null=True)),
                ('municipality', models.CharField(max_length=20, null=True)),
                ('municipality_code', models.IntegerField(null=True)),
                ('federal_entity', models.CharField(max_length=50, null=True)),
                ('federal_entity_key', models.IntegerField(null=True)),
                ('federal_entity_code', models.IntegerField(null=True)),
            ],
        ),
    ]
