# Generated by Django 4.0.10 on 2023-02-18 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zipcodes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zipcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.CharField(max_length=250)),
                ('locality', models.CharField(max_length=250)),
                ('settlement', models.CharField(max_length=100)),
                ('settlement_type', models.CharField(max_length=20)),
                ('settlement_code', models.CharField(max_length=20)),
                ('zone_type', models.CharField(max_length=20)),
                ('municipality', models.CharField(max_length=20)),
                ('municipality_code', models.CharField(max_length=20)),
                ('federal_entity', models.CharField(max_length=50)),
                ('federal_entity_key', models.CharField(max_length=50)),
                ('federal_entity_code', models.CharField(max_length=50)),
            ],
        ),
    ]
