# Generated by Django 4.0.10 on 2023-02-18 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zipcodes', '0002_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zipcode',
            name='federal_entity',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='federal_entity_code',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='federal_entity_key',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='locality',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='municipality',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='municipality_code',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='settlement',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='settlement_code',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='settlement_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='zip_code',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='zone_type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
